# Intro to Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [8]:
np.full(10,2.5)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [19]:
np.arange(3,100)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [26]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
n[1]

array([4, 5, 6])

In [28]:
n[0]

array([1, 2, 3])

In [32]:
n[0,1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
n[0] = [1,2,3]
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
n[:,1]

array([2, 5, 8])

# Randomly-generated arrays

In [46]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise Operations

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [49]:
a + 1

array([1, 2, 3, 4, 5])

In [50]:
a * 2

array([0, 2, 4, 6, 8])

# Comparison operations

In [51]:
a >= 2

array([False, False,  True,  True,  True])

In [61]:
b = 10 * np.random.rand(5)
b

array([5.35604173, 9.53742227, 5.4420816 , 0.82094922, 3.66342402])

In [62]:
a > b

array([False, False, False,  True,  True])

In [63]:
a[a > b]

array([3, 4])

# Summarizing Operations

In [64]:
a

array([0, 1, 2, 3, 4])

In [65]:
a.std()

np.float64(1.4142135623730951)

In [66]:
a.min()

np.int64(0)

In [67]:
a.max()

np.int64(4)