# Linear Algebra Refresher

In [2]:
import numpy as np

In [3]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

# Vector-Vector Multiplication

In [5]:
def vector_vector_mult(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [6]:
vector_vector_mult(u,v)

np.float64(14.0)

In [7]:
u.dot(v)

np.int64(14)

# Matrix-Vector multiplication

In [8]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
U.shape[1]


4

In [9]:
v = np.array([1,.5,2,1])
v.shape[0]

4

In [10]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [11]:
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]

    result = []
    row = 0
    for i in range(U.shape[0]):
        for j in range(U.shape[1]):
            row = row + U[i,j]*v[j]
        result.append(row)
    return result

In [12]:
matrix_vector_mult(U,v)

[np.float64(20.0), np.float64(26.0), np.float64(34.5)]