# Linear Algebra Refresher

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

# Vector-Vector Multiplication

In [4]:
def vector_vector_mult(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [5]:
vector_vector_mult(u,v)

np.float64(14.0)

In [6]:
u.dot(v)

np.int64(14)

# Matrix-Vector multiplication

In [7]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
U


array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [8]:
v = np.array([1,.5,2,1])
v.shape[0]

4

In [9]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [10]:
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]

    result = []
    for i in range(U.shape[0]):
        result.append(vector_vector_mult(U[i],v))
    return result

In [11]:
matrix_vector_mult(U,v)

[np.float64(20.0), np.float64(6.0), np.float64(8.5)]

# Matrix-Matrix Multiplication

In [12]:
V = np.array([[9,8,7],[6,5,4],[3,2,1],[1,1,1]])
V

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1],
       [1, 1, 1]])

In [13]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [14]:
U.dot(V)

array([[63, 52, 41],
       [26, 22, 18],
       [40, 34, 28]])

In [15]:
def matrix_matrix_mult(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows    = U.shape[0]
    num_columns = V.shape[1] 

    result = np.zeros([num_rows,num_columns])
    for i in range(num_columns):
        vi = V[:,i]
        Uvi = matrix_vector_mult(U,vi)
        result[:, i] = Uvi

    return result    

In [16]:
matrix_matrix_mult(U,V)

array([[63., 52., 41.],
       [26., 22., 18.],
       [40., 34., 28.]])

# Identity Matrix

In [17]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Inverse

In [18]:
V = np.array([[1,2],[3,4]])
V

array([[1, 2],
       [3, 4]])

In [19]:
inv = np.linalg.inv(V)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
inv.dot(V)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

## To find the determinant, we cross multiply and subtract

In [21]:
V

array([[1, 2],
       [3, 4]])

In [23]:
det = (V[0,0]*V[1,1]) - (V[1,0]*V[0,1])
det

np.int64(-2)